### ISSUE TITLE
what was your mirror process?

### ISSUE THREAD

**Issue by brannondorsey** [opsxcq/mirror-textfiles.com#2]
This is great! Thanks for this :) Would you mind sharing your mirror process/command?

**Comment by opsxcq** [comment]
In the case of textfiles.com it was just a simple mirror with `wget --mirror`. Everything is static, so its really easy.

Just in case you need, [here](https://www.gnu.org/software/wget/manual/wget.html) is the full documentation of `wget`.

**Comment by brannondorsey** [comment]
Great, thanks!
